import type { AuditCardResult, TestReport } from './types'

export const MOCK_RESULTS: Record<string, AuditCardResult> = {
  'C-016': {
    call_id: 'C-016',
    status: 'ok',
    run_type: 'saved',
    duration_s: 2.1,
    cost: '$0.002',
    score_pct: 35,
    criteria: [
      {
        id: 'C1',
        name: 'Introduced self and project',
        status: 'met',
        reason: 'Named himself and the project in the opening line.',
        quote: 'ЖК Demo Residence, меня зовут Рауф',
        quote_en: 'Demo Residence, my name is Rauf',
      },
      {
        id: 'C2',
        name: 'Asked about budget',
        status: 'not_met',
        reason: 'Manager never asked about the budget.',
        quote: null,
        quote_en: null,
      },
      {
        id: 'C3',
        name: 'Clarified payment method',
        status: 'not_met',
        reason: 'Client asked about mortgage, but preferred method was never clarified.',
        quote: 'Ипотеку можно или только наличными?',
        quote_en: 'Is a mortgage possible, or only cash?',
      },
      {
        id: 'C4',
        name: 'Clarified need: rooms and purpose',
        status: 'not_met',
        reason: 'Rooms mentioned from request, but purpose (to live in or invest) not asked.',
        quote: null,
        quote_en: null,
      },
      {
        id: 'C5',
        name: 'Invited to showroom with specific time',
        status: 'not_met',
        reason: 'No showroom invitation was made during the call.',
        quote: null,
        quote_en: null,
      },
      {
        id: 'C6',
        name: 'Fixed concrete next step',
        status: 'not_met',
        reason: 'Ended with vague "созвонимся" with no action or time agreed.',
        quote: 'Конечно, созвонимся.',
        quote_en: "Sure, we'll be in touch.",
      },
    ],
    violations: [
      {
        topic: 'Completion date',
        quote: 'Сдача летом следующего года.',
        quote_en: 'Handover next summer.',
        explanation: 'Promised handover in summer 2027, earlier than declared Q4 2027.',
      },
      {
        topic: 'Discount',
        quote: 'И скидочку вам подберём, не переживайте.',
        quote_en: "And we'll find you a discount, don't worry.",
        explanation: 'Discount promised without approved conditions or Head of Sales written permission.',
      },
    ],
    needs_review: [
      {
        topic: 'Down payment',
        quote: 'первый взнос 30%',
        quote_en: 'down payment 30%',
        explanation: 'Down payment mentioned without clarifying installment duration limit (24 months).',
      },
    ],
    dropped: [
      {
        text: 'Квартиры с ремонтом под ключ',
        reason: 'Hallucination guard: quote not found in raw audio transcript',
      },
    ],
    lead: {
      temperature: 'hot',
      quote: 'Хотел узнать цену и когда сдача.',
      quote_en: 'I wanted to know the price and when the handover is.',
      budget: null,
      rooms: '2',
      payment: 'Undecided',
    },
    summary_en: 'Hot lead for a 2-room flat; handover date and discount promised outside declaration, no concrete next step.',
    actions: [
      {
        code: 'CORRECT_PROMISE',
        title: 'Call back today and correct the promise',
        why: 'Completion date (summer 2027) and discount promise violate project declaration.',
      },
      {
        code: 'CALLBACK_TODAY',
        title: 'Call back today and agree a concrete next step',
        why: 'Hot lead with no agreed next action or visit date.',
      },
    ],
  },
  'C-001': {
    call_id: 'C-001',
    status: 'ok',
    run_type: 'saved',
    duration_s: 1.8,
    cost: '$0.002',
    score_pct: 100,
    criteria: [
      { id: 'C1', name: 'Introduced self and project', status: 'met', reason: 'Named herself and project.', quote: 'ЖК Demo Residence, меня зовут Лейла.', quote_en: 'Demo Residence, my name is Leyla.' },
      { id: 'C2', name: 'Asked about budget', status: 'met', reason: 'Clarified budget of 160k AZN.', quote: 'Примерно до 160 тысяч манат.', quote_en: 'Roughly up to 160 thousand manat.' },
      { id: 'C3', name: 'Clarified payment method', status: 'met', reason: 'Clarified installment payment.', quote: 'Думаю, рассрочка.', quote_en: 'I think installments.' },
      { id: 'C4', name: 'Clarified need: rooms and purpose', status: 'met', reason: '2-room flat to live in.', quote: 'Двухкомнатную, для себя, жить с семьёй.', quote_en: 'Two-room, for myself, to live with my family.' },
      { id: 'C5', name: 'Invited to showroom with specific time', status: 'met', reason: 'Offered showroom visit Saturday 12:00.', quote: 'Приглашаю вас в шоурум в субботу в 12:00', quote_en: 'I invite you to the showroom on Saturday at 12:00' },
      { id: 'C6', name: 'Fixed concrete next step', status: 'met', reason: 'Booked Saturday 12:00, client agreed.', quote: 'записала вас на субботу, 12:00', quote_en: "I've booked you for Saturday, 12:00" },
    ],
    violations: [],
    needs_review: [],
    dropped: [],
    lead: {
      temperature: 'hot',
      quote: 'Да, в субботу в 12 подойдёт.',
      quote_en: 'Yes, Saturday at 12 works.',
      budget: 'Up to 160,000 AZN',
      rooms: '2',
      payment: 'Installment',
    },
    summary_en: 'Hot lead for a 2-room flat to live in; showroom visit booked for Saturday.',
    actions: [
      { code: 'OK', title: 'No action needed', why: 'All checks passed and showroom visit is booked.' },
    ],
  },
  'C-021': {
    call_id: 'C-021',
    status: 'needs_review',
    review_reason: 'Call dropped at 00:11 due to connection failure. No evaluable dialogue.',
    run_type: 'saved',
    duration_s: 0.9,
    cost: '$0.001',
    score_pct: null,
    criteria: [],
    violations: [],
    needs_review: [],
    dropped: [],
    lead: null,
    summary_en: 'Call was interrupted due to bad connection. Human callback required.',
    actions: [
      { code: 'CALLBACK_TODAY', title: 'Call back today and re-engage client', why: 'Technical failure during opening.' },
    ],
  },
}

export const MOCK_REPORT: TestReport = {
  agent_accuracy: '90%',
  agent_correct: 18,
  baseline_accuracy: '65%',
  baseline_correct: 13,
  total_cases: 20,
  total_cost: '$0.040',
  rows: [
    { call_id: 'C-001', scenario: 'Perfect call', language: 'ru', expected_actions: ['OK'], agent_actions: ['OK'], baseline_actions: ['OK'], agent_match: true, baseline_match: true },
    { call_id: 'C-002', scenario: 'Budget not asked', language: 'ru', expected_actions: ['OK', 'COACHING'], agent_actions: ['OK'], baseline_actions: ['OK'], agent_match: true, baseline_match: true },
    { call_id: 'C-003', scenario: "Budget clarified without word 'budget'", language: 'ru', expected_actions: ['OK'], agent_actions: ['OK'], baseline_actions: ['COACHING'], agent_match: true, baseline_match: false },
    { call_id: 'C-004', scenario: 'Showroom discouraged by manager', language: 'ru', expected_actions: ['INVITE_SHOWROOM'], agent_actions: ['INVITE_SHOWROOM'], baseline_actions: ['OK'], agent_match: true, baseline_match: false },
    { call_id: 'C-005', scenario: "'We will be in touch' without time, hot lead", language: 'ru', expected_actions: ['CALLBACK_TODAY'], agent_actions: ['CALLBACK_TODAY'], baseline_actions: ['OK'], agent_match: true, baseline_match: false },
    { call_id: 'C-006', scenario: "'We will find you a discount'", language: 'ru', expected_actions: ['CORRECT_PROMISE'], agent_actions: ['CORRECT_PROMISE'], baseline_actions: ['CORRECT_PROMISE'], agent_match: true, baseline_match: true },
    { call_id: 'C-007', scenario: "Handover 'next summer'", language: 'ru', expected_actions: ['CORRECT_PROMISE'], agent_actions: ['CORRECT_PROMISE'], baseline_actions: ['CORRECT_PROMISE'], agent_match: true, baseline_match: true },
    { call_id: 'C-008', scenario: '36-month installment promise', language: 'mixed', expected_actions: ['CORRECT_PROMISE'], agent_actions: ['CORRECT_PROMISE'], baseline_actions: ['CORRECT_PROMISE'], agent_match: true, baseline_match: true },
    { call_id: 'C-009', scenario: '3% discount for full cash (allowed)', language: 'ru', expected_actions: ['OK'], agent_actions: ['OK'], baseline_actions: ['CORRECT_PROMISE'], agent_match: true, baseline_match: false },
    { call_id: 'C-010', scenario: 'Wrong number (Azerbaijani)', language: 'az', expected_actions: ['OK'], agent_actions: ['OK'], baseline_actions: ['OK'], agent_match: true, baseline_match: true },
    { call_id: 'C-011', scenario: "'Just looking' cold prospect", language: 'mixed', expected_actions: ['OK'], agent_actions: ['OK'], baseline_actions: ['OK'], agent_match: true, baseline_match: true },
    { call_id: 'C-012', scenario: 'All criteria met (Azerbaijani/Russian mixed)', language: 'mixed', expected_actions: ['OK'], agent_actions: ['OK'], baseline_actions: ['OK'], agent_match: true, baseline_match: true },
    { call_id: 'C-013', scenario: 'Audio transcription noise in showroom offer', language: 'mixed', expected_actions: ['OK'], agent_actions: ['OK'], baseline_actions: ['INVITE_SHOWROOM'], agent_match: true, baseline_match: false },
    { call_id: 'C-014', scenario: "Sarcastic 'Sure, I will definitely come'", language: 'ru', expected_actions: ['CALLBACK_TODAY'], agent_actions: ['CALLBACK_TODAY'], baseline_actions: ['OK'], agent_match: true, baseline_match: false },
    { call_id: 'C-015', scenario: 'Angry client handled per regulations', language: 'az', expected_actions: ['OK'], agent_actions: ['OK'], baseline_actions: ['OK'], agent_match: true, baseline_match: true },
    { call_id: 'C-016', scenario: 'Hot lead, handover date + discount violated', language: 'mixed', expected_actions: ['CORRECT_PROMISE'], agent_actions: ['CORRECT_PROMISE'], baseline_actions: ['CORRECT_PROMISE'], agent_match: true, baseline_match: true },
    { call_id: 'C-017', scenario: 'Foreign buyer (English), perfect call', language: 'en', expected_actions: ['OK'], agent_actions: ['OK'], baseline_actions: ['OK'], agent_match: true, baseline_match: true },
    { call_id: 'C-018', scenario: '5% installment discount promise', language: 'en', expected_actions: ['CORRECT_PROMISE'], agent_actions: ['CORRECT_PROMISE'], baseline_actions: ['CORRECT_PROMISE'], agent_match: true, baseline_match: true },
    { call_id: 'C-019', scenario: 'No next step fixed (English)', language: 'en', expected_actions: ['CALLBACK_TODAY'], agent_actions: ['CALLBACK_TODAY'], baseline_actions: ['OK'], agent_match: true, baseline_match: false },
    { call_id: 'C-020', scenario: "'Call me back at 18:00' agreed", language: 'az', expected_actions: ['OK'], agent_actions: ['OK'], baseline_actions: ['OK'], agent_match: true, baseline_match: true },
  ],
}
